package io.hashimati.domains;

/**
 * @author Ahmed Al Hashmi @hashimati
 *
 */
public enum MessageCode {
    RESETTING_PASSWORD,DUPLICATED , INVALID_USER , INVALID_JOB_APPLICATION, INVALID_JOB_POSTING, ALLREADY_APPLIED_FOR_THIS_JOB,JOB_NOT_OPEN,
    POST_SUCCESS_MESSAGE, EMAIL_DOES_NOT_EXIST, FAILED_TO_RESET_PASSWORD, SUCCESS_RESET_PASSWORD, INVALID_JOB_PUBLISHING, FAILED_TO_PUBLISH_JOB, PUBLISHING_JOB, INVALID_JOB_BANNER_UPLOAD, INVALID_JOB_BANNER_FILE_SIZE, FAILED_TO_UPLOAD_JOB_BANNER, SUCCESSFULLY_UPLOAD_JOB_BANNER, INVALID_INQUIRY, APPLICANT_INQUIRY, EXPIRED_JOB_APPLICATION;
}
